### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by dan2735** [birdbrainswagtrain/GmodPillPack#6]
Hey, so I have the Parakeet Pill Pack and I was wondering if anyone would be able to help me? I ripped the addon apart to the basics and deleted a bunch of files and modified a bunch of files so the only thing you can do is morph into the 3 birds. Everything totally works, the physics works, the morphing works, the only thing that does not work is the model drawing. I can even see the shadow of the bird model, but the model itself is not visible, I would appreciate any guidance. 

I understand if you refuse to give support, but I’m just asking for a little help.

**Comment by birdbrainswagtrain** [comment]
Is this file correct? Does it match your version?

https://github.com/birdbrainswagtrain/GmodPillPack/blob/b60646d1bb9fd97c0ce95e5e047335e40ecebf14/lua/entities/pill_puppet.lua

If not then I don't know how I can help. There are probably dozens of other reasons this could happen if you decided to take the addon apart and delete a bunch of stuff.

**Comment by dan2735** [comment]
Thanks a lot, I guess I had an old version, It was missing the ENT:Draw function. 

Wonder why?
